### ISSUE TITLE
Problems in Combination with Hair Shader

### ISSUE THREAD

**Issue by the-real-tokai** [FireKDragon/NetCreator#1]
CINEMA 4D supports adding a simple `Hair shader` material to splines to render them out without having to generate actual geometry in the scene (so no need for a Sweep object.)

For some reason this doesn't work with `NetCreator`. Adding a Hair material to the generated spline construct doesn't do a thing. Similar adding a `Hair Render` tag is a fruitless operation too. Nothing can get rendered out.

For static images one can workaround it by making the `NetCreator`object editable, then it works. But of course this makes things pointless for animations.

---

Also only the encrypted version of the plugin is available here on GitHub (no actual code is in the code repository :-o ), so I sadly can't check the code myself what the problem could be.

**Comment by LewisOrton** [comment]
I don't have the code right now (and I am not even sure if it still exists somewhere) but I believe it's registered as the common object, not spline object, that's why you can't directly render it as hair. There was a reason for this but I don't remember. If you use Octane you can assign an OctaneObject Tag for NetCreator, and use the "render as hair" function to directly render it out without sweeping it as polygon.

The other workaround is that you can create a hair object and use the NetCreator as the source, so you can easily render it out as hair with the native standard renderer. I've moved onto Houdini so this project is not going to be developed any further.

Hope this is helpful for you.

**Comment by the-real-tokai** [comment]
Thanks for feedback. I don't have Octane, but the Hair object method could work (albeit quite a bit more work to setup). Need to test how well it performs during animation, etc.

Maybe you can put the code into the repository, when you find it, then we could tinker with it and adapt it to our needs, if necessary and a project requires it. It seems to be a nice enough plugin, so it would be a shame if disappears in abandonment. :)

**Comment by LewisOrton** [comment]
Hi, I found a copy of the source code in a dusty corner and it's released as open-sourced files now :)

**Comment by the-real-tokai** [comment]
Thanks for sharing. :-)
